baseURL: https://adityakhurana.netlify.app/
languageCode: en-us
title: Portfolio Website for Aditya Khurana
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
#    buttonText: Get Started
    subtitle: |-
      Hey, I am Aditya. Welcome to my website!
    title: Aditya Khurana
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Paddington
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: akhurana.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7880333637
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Aditya Khurana
    enable: yes
    quicklinks:
#      - alt: 
#        text: 
#        url: 
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/adityakhurana27/
      - icon: fa-github
        label: GitHub
        url: https://github.com/akadityakhurana
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/aditya-khurana/
  image: ''
  name: Your name
  navigation:
#    button1:
#      - name: Get Started
#        url: blogs
    #button2:
    #  - name: Log In
    #    url: '#'
    links:
      - name: Home
        url: '#'
      - name: This is me
        url: blogs/aboutme
      - name: My Portfolio
        url: portfolio
      - name: My CV
        url: blogs/cv
    menu: Menu
    subtitle: By Aditya Khurana
    title: Now I know R
  tiles:
    enable: yes
    showcase:
      - image: omega.jpg
        subtitle:
        title: Let's talk about Pay Discrimination
        url: portfolio/omega
      - image: alcohol.jpg
        subtitle: 
        title: How much do we drink?
        url: portfolio/drink
      - image: weather.jpg
        subtitle: 
        title: Is Climate Change real?
        url: portfolio/climate
      - image: biden.jpg
        subtitle: 
        title: Do we really like Biden?
        url: portfolio/biden
#  two:
#    buttonText: Get Started
#    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
#    title: Massa libero
#    url: blogs
