---
categories:
- ""
- ""
date: "2017-10-31T22:26:09-05:00"
description:
draft: false
image: climate.jpg
keywords: ""
slug: climate
title: Is Climate Change real?
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies you need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)
spec(weather)</code></pre>
<pre><code>## cols(
##   Year = col_double(),
##   Jan = col_double(),
##   Feb = col_double(),
##   Mar = col_double(),
##   Apr = col_double(),
##   May = col_double(),
##   Jun = col_double(),
##   Jul = col_double(),
##   Aug = col_double(),
##   Sep = col_double(),
##   Oct = col_double(),
##   Nov = col_double(),
##   Dec = col_double(),
##   `J-D` = col_double(),
##   `D-N` = col_double(),
##   DJF = col_double(),
##   MAM = col_double(),
##   JJA = col_double(),
##   SON = col_double()
## )</code></pre>
<p>For each month and year, the dataframe shows the deviation of temperature from the normal (expected). Further the dataframe is in wide format.</p>
<pre class="r"><code>tidyweather &lt;- weather %&gt;%
  select(1:13) %&gt;%
  pivot_longer(cols = 2:13, 
              names_to = &quot;Month&quot;, 
              values_to = &quot;delta&quot;)
  
tidyweather</code></pre>
<pre><code>## # A tibble: 1,704 x 3
##     Year Month delta
##    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1  1880 Jan   -0.35
##  2  1880 Feb   -0.51
##  3  1880 Mar   -0.23
##  4  1880 Apr   -0.3 
##  5  1880 May   -0.06
##  6  1880 Jun   -0.16
##  7  1880 Jul   -0.18
##  8  1880 Aug   -0.26
##  9  1880 Sep   -0.23
## 10  1880 Oct   -0.32
## # ... with 1,694 more rows</code></pre>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date, label=TRUE), 
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;,
    x = &quot;Year&quot;,
    y = &quot;Delta&quot; 
  )+
  NULL</code></pre>
<p><img src="/portfolio/climate_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><img src="/portfolio/climate_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" />
Is the effect of increasing temperature more pronounced in some months?</p>
<p>After observing the graphs, we have come to the conclusion that colder/winter months such as November to March have temperature deviations that are more pronounced than in other months. In other words, the temperature during these months tend to deviate the most above what is expected. There are more hotter days than expected during these months.</p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calculates a temperature anomaly, as difference from the base period of 1951-1980. The code below creates a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, wecreate a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  ) +
  NULL</code></pre>
<p><img src="/portfolio/climate_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta = mean(delta, na.rm = TRUE)) 

#plotting the data:
ggplot(average_annual_anomaly, aes(x= Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth(method = &quot;loess&quot;) +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  ) +
  NULL</code></pre>
<p><img src="/portfolio/climate_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 

  # choose the interval 2011-present
  # what dplyr verb will you use? 
  filter(interval == &quot;2011-present&quot;) %&gt;%

  # calculate summary statistics for temperature deviation (delta)
  # calculate mean, SD, count, SE, lower/upper 95% CI
  summarise(
    mean_delta = mean(delta, na.rm = TRUE),
    SD_delta = sd(delta, na.rm = TRUE),
    count_delta = n(),
    SE_delta = SD_delta/sqrt(count_delta),
    t_crit = qt(0.975, count_delta-1),
    CI_low = mean_delta -t_crit * SE_delta,
    CI_high = mean_delta +t_crit * SE_delta
  )
  
  
#print out formula_CI
formula_ci</code></pre>
<pre><code>## # A tibble: 1 x 7
##   mean_delta SD_delta count_delta SE_delta t_crit CI_low CI_high
##        &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
## 1       1.06    0.274         132   0.0239   1.98   1.01    1.11</code></pre>
<pre class="r"><code>library(infer)

set.seed(123456789)

CI_bootstrap &lt;- comparison %&gt;%
  group_by(interval) %&gt;%
  filter(interval == &quot;2011-present&quot;) %&gt;%
  specify(response = delta) %&gt;%
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  calculate(stat = &quot;mean&quot;) %&gt;%
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)
  
CI_bootstrap </code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.01     1.10</code></pre>
<blockquote>
<p>What is the data showing us?</p>
</blockquote>
<p>We constructed confidence interval for the average annual delta since 2011 by using formula for calculation and using a bootstrap simulation. Two methods showed a 95% confidence interval of [1.01, 1,11]. Therefore, we are 95% confident that the average monthly temperature anomalies is between 1.01 and 1.11.</p>
</div>
</div>
